# Generated by Django 2.0.7 on 2018-07-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('activeIngredient', models.CharField(max_length=80)),
                ('laboratory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('24', '24 hours'), ('12', '12 hours'), ('8', '8 hours'), ('6', '6 hours'), ('4', '4 hours'), ('2', '2 hours')], max_length=2)),
                ('isactive', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('time_frame_days', models.IntegerField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p1.Medicine')),
            ],
        ),
    ]
